### ISSUE TITLE
[Request] Support for Iguana Tweaks' Regenerating Absorption

### ISSUE THREAD

**Issue by MidasMischief** [Lanfix8/SimpleHealthBar-Fabric#10]
Hi! I'm requesting a feature for Simple Health Bar for Forge 1.20.1, basically the mod Iguana Tweaks adds a new bar called regenerating absorption that replaces armor toughness, It acts similar to regular absorption except it regenerates itself, it could appear above the health bar as a blue bar for example.

**Comment by Lanfix8** [comment]
Can you show me how both mods together look at the moment ?

**Comment by Lanfix8** [comment]
Sorry, I am not working anymore on the Forge version, mainly because it is annoying to work on.
I might try using NeoForge later if it gets popular and if it is easy to develop on.
Thanks for downloading Simple Health Bar
