### ISSUE TITLE
Backport to 1.21

### ISSUE THREAD

**Issue by Tenuuu** [Lanfix8/SimpleHealthBar-Fabric#17]
Would it be possible for the mod to be compatible with 1.21?

**Comment by Lanfix8** [comment]
It already is ?
https://modrinth.com/mod/simple-health-bar/version/VfiDfHas
@Tenuuu Did you mean the 1.1.1 update ?

**Comment by Tenuuu** [comment]
Yeah I meant the 1.1.1 update! My bad, totally forgot to mention that portion

**Comment by Lanfix8** [comment]
I am sorry, but I don't think I will do this (If I do it, it will be in October/November because I don't have time at the moment)
Thanks for downloading Simple Health Bar !
