### ISSUE TITLE
add support for 1.19.2

### ISSUE THREAD

**Issue by elifian** [Lanfix8/SimpleHealthBar-Fabric#20]
Please

**Comment by Lanfix8** [comment]
Ok I'm doing it this week.

**Comment by Lanfix8** [comment]
Hello
I created the 1.19.2 version of the mod !
It is already on modrinth [here](https://modrinth.com/mod/simple-health-bar/version/kgZ7VjWS)
Commit: https://github.com/Lanfix8/SimpleHealthBar-Fabric/commit/676e5c2bddca0ddbbeec8253b6440843b19f5c65
Thanks for downloading my mod and have fun playing !
