### ISSUE TITLE
Bars are under overlays

### ISSUE THREAD

**Issue by Astracyn** [Lanfix8/SimpleHealthBar-Fabric#5]
As demonstrated here, the health bar appears below any overlays (most notably the nether portal overlay, but also vignettes).
![image](https://github.com/Lanfix8/SimpleHealthBar-Fabric/assets/115433521/e9e13314-1e7e-499b-9a35-2f25dcc3e365)

This has been an issue in the mod for a while (I suspect since 928c8aec1accce84d9afd53a77f9846b3f3a663a, though I haven't tested), but I haven't quite figured out why or how to fix it.

**Comment by Astracyn** [comment]
This has been fixed in my fork at 82a58ed26b22dfeb63587a7e1627c1c3109704ca -- it was actually quite a simple fix, by just `Redirect`ing the original health bar's invoke to the new `healthBar.render()` function. Blends behind chat *and* works with overlays!

**Comment by Lanfix8** [comment]
I don't know how I only see this now, but I'll look into this soon, thank you !

**Comment by Lanfix8** [comment]
Hello
Today I had time to work on it, so I fixed this, I made a couple other changes so it fits well.
If you want to check the new version on modrinth : https://modrinth.com/mod/simple-health-bar/version/J2OYBazD
Otherwise the code is also here on github.
Thank you for your help !
