### ISSUE TITLE
health caps at 1024

### ISSUE THREAD

**Issue by BaffledHedgehog** [Lanfix8/SimpleHealthBar-Fabric#6]
health bar caps on 1024 Health, even if i have way more

**Comment by Lanfix8** [comment]
Ok
I'm gonna look into it when I have the time !

**Comment by Lanfix8** [comment]
Hello
It has nothing to do with my mod, and that's simply because minecraft limits the maximum health to 1024 and you cannot go above.
Have a nice day.
