### ISSUE TITLE
food bar

### ISSUE THREAD

**Issue by Hainer007** [Lanfix8/SimpleHealthBar-Fabric#7]
Add a food bar pls and a text health switch

**Comment by Lanfix8** [comment]
Hello,
I don't think there is much interest in a food bar, as you cannot change your maximum food in minecraft.
And what do you mean by "text health switch" ?

**Comment by Astracyn** [comment]
I believe they're talking about a configuration option to turn off the number showing the health that is normally next to the health bar.

**Comment by Astracyn** [comment]
Looks like #9 is also requesting this!

**Comment by noawx** [comment]
While the existence of a custom food/armor/oxygen bar would be useless, I think it would be cool for visual consistency.

**Comment by Lanfix8** [comment]
> While the existence of a custom food/armor/oxygen bar would be useless, I think it would be cool for visual consistency.

I wanted this mod to be just a health bar, and try to blend it into the minecraft gui.
As I see many people are asking for this I think I'll do another mod to do all status bars (I don't have much time right now but it'll be on the list)

Thank you all for your feedbacks.

**Comment by Hainer007** [comment]
I will be very polite to you if you do!

ср, 22 трав. 2024 р., 19:37 користувач Lanfix ***@***.***>
пише:

**Comment by Lanfix8** [comment]
Hello everyone

I finally created my new mod: All HUD Bars
It adds all status bars from minecraft, including the food bar that you requested.
You can visit its [github repository](https://github.com/Lanfix8/AllHUDBars).
You can download it from [modrinth](https://modrinth.com/mod/all-hud-bars) or [curseforge](https://www.curseforge.com/minecraft/mc-mods/all-hud-bars) !

Thanks for your participation to the project !
